# Generated by Django 2.0.7 on 2018-12-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_ID', models.IntegerField()),
                ('CASE_NAME', models.CharField(max_length=40)),
                ('MODEL_NAME', models.CharField(max_length=40)),
                ('ADDR', models.CharField(max_length=256)),
                ('ADDTIME', models.DateTimeField(null=True)),
                ('SIGN', models.CharField(max_length=5, null=True)),
                ('STATUS', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_ID', models.IntegerField()),
                ('CASE_NAME_DETAIL', models.CharField(max_length=128)),
                ('MODEL_NAME', models.CharField(max_length=128)),
                ('CASE_OWNER', models.CharField(max_length=128, null=True)),
                ('ADDR', models.CharField(max_length=256)),
                ('TEST_RESULT', models.CharField(max_length=20, null=True)),
                ('MESSAGE', models.CharField(max_length=512, null=True)),
                ('DURATION', models.CharField(max_length=20, null=True)),
                ('STARTTIME', models.CharField(max_length=20, null=True)),
                ('ENDTIME', models.CharField(max_length=20, null=True)),
                ('ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='uiATMod.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseTMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_ID', models.IntegerField()),
                ('CASE_NAME', models.CharField(max_length=40)),
                ('MODEL_NAME', models.CharField(max_length=40)),
                ('ADDR', models.CharField(max_length=256)),
                ('ADDTIME', models.DateTimeField(null=True)),
                ('SIGN', models.CharField(max_length=5, null=True)),
                ('STATUS', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
