version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "[!]%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s : %(message)s"
#            format: "[!]%(asctime)s - %(name)s - %(filename)s[line:%(lineno)d] - %(levelname)s : %(message)s"
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: .\log\detail.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: .\log\errors.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8

loggers:
    main:
            level: ERROR
            handlers: [console,error_file_handler]
            propagate: no
    detail:
            level: INFO
            handlers: [console,info_file_handler]
            propagate: no
root:
    level: INFO
    handlers: [console,info_file_handler,error_file_handler]